services:
  app:
    restart: unless-stopped
    build:
      context: ./app
    env_file:
      - .env.app
    ports:
      - 80:80
    depends_on:
      - db
      - redis
      - celery

  celery:
    restart: unless-stopped
    build:
      context: ./app
    env_file:
      - .env.app
    command: celery -A cyclerent worker -l info
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    env_file:
      - .env.db

  redis:
    image: redis:7.2.5-alpine
